### ISSUE TITLE
Blank project codes get mapped to unfound projects

### ISSUE THREAD

**Issue by camfowler** [camfowler/md#9]
When there are entries without a project code, and you have a project code configured in ~/.md.yml that doesn't exist, md matches them up and creates matching entries in the secondary minutedock account.

It shouldn't do this.

**Comment by ndorfin** [comment]
```
---
ApiKey: "x"

AccountID: 1869
MappedAccountID: 16411

ProjectMaps:
  ae_merchant_self_service_portal​: "ae_eftplus_and_merchant_portal"
  other_team_meetings: "team_meetings"
---
```

In my case I got double entries for each entry not matching the given project name.

![screen shot 2016-08-05 at 11 58 21 am](https://cloud.githubusercontent.com/assets/107569/17423645/62b2e516-5b10-11e6-8169-8ba18b43bfc5.png)
